package com.xperience.hero.invitation;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.xperience.hero.event.Event;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Invitation domain entity, per DESIGN.md Section 8 (Data Ownership and
 * State Model — "Invitation" row) and I7 (Invitation Scope).
 *
 * Represents only what is currently determined: an Invitation belongs to
 * exactly one Event and identifies an invited email address, plus the
 * one-way hash of its unique invitation token. The raw token is never
 * stored — only its hash, generated by InvitationTokenService.
 *
 * Deliberately NOT represented here: RSVP Response, Attendance Outcome, or
 * any waitlist/confirmed state (all separate concepts per DESIGN.md Section
 * 8, not implemented in this slice); token expiry (Q9, unresolved); any
 * invitee account/authentication model (Q2, unresolved). There is also no
 * uniqueness constraint on (event, inviteeEmail) — whether duplicate
 * invitations to the same email are allowed is unresolved (Q8); this is not
 * silently decided by the schema.
 *
 * The invitation token is a completely separate concept from the event's
 * host management token (DESIGN.md Q3) — see InvitationTokenService, which
 * shares no code with HostTokenService.
 */
@Entity
@Table(name = "invitations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Invitation {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    @Column(name = "invitee_email", nullable = false)
    private String inviteeEmail;

    /**
     * SHA-256 hash of the backend-generated invitation token. The raw token
     * is never stored here and never logged; only this one-way hash is
     * persisted. Must never be exposed directly in any API response —
     * @JsonIgnore is a defense-in-depth backstop should this entity ever be
     * serialized directly.
     */
    @JsonIgnore
    @Column(name = "invitation_token_hash", nullable = false)
    private String invitationTokenHash;
}
